### ISSUE TITLE
脱敏后数据不一致

### ISSUE THREAD

**Issue by menghuan** [ECNU-1X/DataX-Masking#2]
2张表都有手机号字段 同一个uid下手机号通过2个json脚本 脱敏后 数据不一样 怎么解决这种 多表相同id中相同字段脱敏后一致性问题 谢谢

**Comment by menghuan** [comment]
用的此脱敏方法 Prefix Preserve | 保持前n位不变，混淆其余部分。可针对字母和数字字符在同为字母或数字范围内进行混淆，特殊符号将保留
-- | --

**Comment by build2last** [comment]
> 2张表都有手机号字段 同一个uid下手机号通过2个json脚本 脱敏后 数据不一样 怎么解决这种 多表相同id中相同字段脱敏后一致性问题 谢谢

Thanks for your issue! 
问题已收到，我们会关注您提到的一致性问题并对相关算法进行review！
