### ISSUE TITLE
编译时,各插件的libs文件夹缺失

### ISSUE THREAD

**Issue by xinuo** [ECNU-1X/DataX-Masking#3]
datax-masking的项目clone下来后,编译时候提示文件缺失,查看pom.xml:
`		<dependency>
			<groupId>com.oracle</groupId>
			<artifactId>ojdbc6</artifactId>
			<version>11.2.0.3</version>
			<scope>system</scope>
            <systemPath>${basedir}/src/main/lib/ojdbc6-11.2.0.3.jar</systemPath>
		</dependency>`
由上可知文件处于${basedir}/src/main/lib/ 里,但项目里面没有.去datax主项目查看过是有的.
以上缺失包括且不仅oraclewriter,sqlserverreader,sqlserverwriter等等.
所以datax-masking可能在处理的过程中缺失了这块的文件.望知晓.

**Comment by build2last** [comment]
We mistake to ignore all jar by adding *.jar to .gitignore.
Fixed in the latest commit by adding those jar.
